language: node_js
node_js:
  - 'lts/*'
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: surge
  project: ./dist/
  domain: frontend-challenge-vue.surge.sh
  skip_cleanup: true
